### ISSUE TITLE
Switch code highlight engine to pygments?

### ISSUE THREAD

**Issue by z-a-f** [le4ker/personal-jekyll-theme#138]
Highlight.js might not the best highlighter choice because for codes with a lot of `<` and `>`, it requires manual escaping of the characters with `&lt;` and `&gt;`. For example try this piece of markdown:

```
# Code 1

<pre><code class="c++">
vector< vector<int> > A;
</code></pre>

# Code 2
<pre><code class="c++">
A = vector<> foo();
</code></pre>
```

**Comment by PanosSakkos** [comment]
Good point. 

I [asked](https://twitter.com/thepanoss/status/688467265164042240) them and I will update the issue here when they reply.

**Comment by dwendt** [comment]
imo why not switch to a more reliable highlighting engine like pygments

**Comment by PanosSakkos** [comment]
@dwendt Thanks for the suggestion! 

Can you pleas briefly list the benefits of pygments over the current solution?

**Comment by eiselems** [comment]
relevant: https://help.github.com/articles/using-syntax-highlighting-on-github-pages/

**Comment by djcaesar9114** [comment]
Actually I asked myself the same question. I don't know if you noticed, but in the present form of {{personal}}, a blank line is added everytime you highlight a code.
I transformed every `<pre><code>` into `{% highlight bash %}`.
I'll try and make a branch on my fork to make a pull request here, so that you can see the changes.
It will be a good training for me :)
