### ISSUE TITLE
Generate intermediate blog collection pages for year, month and date

### ISSUE THREAD

**Issue by Ken4scholars** [le4ker/personal-jekyll-theme#233]
## Questions
It would be great if individual pages could be generated for each day, month and year with blog posts.
For example, if I wrote a blog post on June 1, 2018, the url will be `http://<base_url>/<category>/2018/06/01/<slug>`. It would be great if readers could navigate to `http://<base_url>/<category>/2018/06/01` and get the list of posts for June 1, 2018 and navigate to `http://<base_url>/<category>/2018/06` to get the list of posts for the month of June 2018 and so on.

## Expected Behavior

Be able to navigate to list of posts for a day, month and year with available blog posts.

## Actual Behavior
No such available pages. 

## Steps to Reproduce the Issue

  1. Navigate to a blog post
  2. Navigate to the day, month or year of the post
  3. Page displays 404

## Specifications

(The version of the project, browser etc.)

**Comment by eiselems** [comment]
Hi @Ken4scholars,

I had a quick look at it. Sadly I am pretty sure that it is not that easy.
Especially since I guess this is a Jekyll feature and not a feature of this theme.

We could add a plugin for it but it will not work on github then.
Maybe you could move your feature request over to [https://github.com/jekyll/jekyll](https://github.com/jekyll/jekyll)?

I am really pro against adding plugins which will not be supported by github pages.
(A way to do so would be described here: https://joseoncode.com/2011/11/27/generating-monthly-archives-with-jekyll/)

I forwarded your issue to https://gitter.im/jekyll/jekyll and see what comes back.
Really would like the functionality myself.

**Comment by Ken4scholars** [comment]
Hello @eiselems. Thanks for the reply. I actually took a look at it myself later on and saw that it isn't an easy task too and shouldn't be confined to the theme as it is more of a generic problem for Jekyll itself. And you're are right about adding plugins, they don't play well with Github pages unless they are supported. I'm using one myself and I always have to build the static pages before deploying, which add a lot of complexity to the process. Thank you for forwarding the issue. I will keep an eye on it.

**Comment by eiselems** [comment]
Seems there is not much going on inside the jekyll gitter. Maybe it would be the best if you report it directly to jekyll instead. See; https://github.com/jekyll/jekyll
